[package]
name = "rust-history"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
crossterm = "0.27.0"

[build-dependencies]
cc   = "1.0.83"
libc = "0.2.150"